spring:
  main:
    banner-mode: off

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml

  jpa:
    show-sql: true
    hibernate:
       ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    web: debug
#logging:
#  level:
#    org.springframework.web: debug
#    org.hibernate: debug
##    org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#    org: info

server:
  port : 8081