DROP FUNCTION IF EXISTS public.get_balance_account(uuid);

DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS agreements;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS managers;
DROP TABLE IF EXISTS users;